// Module2_FrontendDev/PrasannaSaiS/handson_06/src/components/Header.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';

function Header() {
  const enrolledCourses = useSelector(state => state.enrollment.enrolledCourses);
  const enrolledCount = enrolledCourses.length;

  return (
    <header className="site-header glass">
      <Link to="/" className="site-title">Student Portal</Link>
      <nav aria-label="Primary navigation">
        <ul className="nav-links">
          <li><Link to="/">Home</Link></li>
          <li>
            <Link to="/courses">
              Courses
              {enrolledCount > 0 && <span className="badge">{enrolledCount}</span>}
            </Link>
          </li>
          <li><Link to="/profile">Profile</Link></li>
        </ul>
      </nav>
    </header>
  );
}

export default Header;

// Module2_FrontendDev/PrasannaSaiS/handson_08/student-portal-vue/src/components/Header.vue
<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<template>
  <header class="site-header glass">
    <RouterLink to="/" class="site-title">Student Portal</RouterLink>
    <nav aria-label="Primary navigation">
      <ul class="nav-links">
        <li><RouterLink to="/">Home</RouterLink></li>
        <li>
          <RouterLink to="/courses">
            Courses
            <span v-if="store.enrolledCourses.length > 0" class="badge">
              {{ store.enrolledCourses.length }}
            </span>
          </RouterLink>
        </li>
        <li><RouterLink to="/profile">Profile</RouterLink></li>
      </ul>
    </nav>
  </header>
</template>
