// Module2_FrontendDev/PrasannaSaiS/handson_05/src/components/Header.jsx
import React from 'react';

function Header({ siteName, enrolledCount }) {
  return (
    <header className="site-header glass">
      <a href="#" className="site-title">{siteName}</a>
      <nav aria-label="Primary navigation">
        <ul className="nav-links">
          <li><a href="#home">Home</a></li>
          <li>
            <a href="#courses">
              Courses
              {enrolledCount > 0 && <span className="badge">{enrolledCount}</span>}
            </a>
          </li>
          <li><a href="#profile">Profile</a></li>
        </ul>
      </nav>
    </header>
  );
}

export default Header;

// Module2_FrontendDev/PrasannaSaiS/handson_08/student-portal-vue/src/components/Header.vue
<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<template>
  <header class="site-header glass">
    <RouterLink to="/" class="site-title">Student Portal</RouterLink>
    <nav aria-label="Primary navigation">
      <ul class="nav-links">
        <li><RouterLink to="/">Home</RouterLink></li>
        <li>
          <RouterLink to="/courses">
            Courses
            <span v-if="store.enrolledCourses.length > 0" class="badge">
              {{ store.enrolledCourses.length }}
            </span>
          </RouterLink>
        </li>
        <li><RouterLink to="/profile">Profile</RouterLink></li>
      </ul>
    </nav>
  </header>
</template>
